### ISSUE TITLE
Write a `README` 

### ISSUE THREAD

**Issue by priyanshumaitra** [priyanshumaitra/YouTube-Clone#10]
Write a `README` that helps beginners and others to contribute to this project.
From setting up the environment, installing Git and everything that they need to contribute.
Effected file: `README.md`

**Comment by thatsuman** [comment]
Assign me this issue

**Comment by priyanshumaitra** [comment]
@thatsuman Go ahead :crying_cat_face:

**Comment by priyanshumaitra** [comment]
> Assign me this issue

?

**Comment by thatsuman** [comment]
> > Assign me this issue
> 
> ?

??
