### ISSUE TITLE
Feature: Make the site responsive

### ISSUE THREAD

**Issue by priyanshumaitra** [priyanshumaitra/YouTube-Clone#19]
As the site is not responsive yet, so the video recommendation section is appearing differently in other resolutions, except in `1920 x 1080` resolution.

**Comment by HammadKhaan** [comment]
@priyanshumaitra assign this issue to me, please.

**Comment by priyanshumaitra** [comment]
> @priyanshumaitra assign this issue to me, please.

Sure! Go ahead.

**Comment by priyanshumaitra** [comment]
@HammadKhaan Make sure to pull the changes to avoid merge conflicts. Thanks.

**Comment by priyanshumaitra** [comment]
@HammadKhaan Are you still working on this issue?

**Comment by HammadKhaan** [comment]
@priyanshumaitra No, assign it to someone else.

**Comment by priyanshumaitra** [comment]
> @priyanshumaitra No, assign it to someone else.

Alright
