### ISSUE TITLE
The `Search Bar` is too large than the actual one

### ISSUE THREAD

**Issue by su1nta** [priyanshumaitra/YouTube-Clone#20]
The Search Bar on the Clone site:

![search-clone](https://user-images.githubusercontent.com/62897008/196694902-7d6f191e-988d-404c-9f72-2e292acbd869.png)

The Search Bar on the Actual site:

![search-actual](https://user-images.githubusercontent.com/62897008/196695026-6fbd594e-3658-4c77-a8fc-28d4172ef5e4.png)

- The width of the search bar needs to be reduced
- The search and the mic icon needs to be tweaked

**Comment by priyanshumaitra** [comment]
> The Search Bar on the Clone site:
> 
> ![search-clone](https://user-images.githubusercontent.com/62897008/196694902-7d6f191e-988d-404c-9f72-2e292acbd869.png)
> 
> The Search Bar on the Actual site:
> 
> ![search-actual](https://user-images.githubusercontent.com/62897008/196695026-6fbd594e-3658-4c77-a8fc-28d4172ef5e4.png)
> 
> - The width of the search bar needs to be reduced
> - The search and the mic icon needs to be tweaked

Thanks for pointing out. Assigning you @su1nta
