### ISSUE TITLE
Adding hover effect on the tags below search bar

### ISSUE THREAD

**Issue by skk401** [priyanshumaitra/YouTube-Clone#23]
![utb](https://user-images.githubusercontent.com/95235016/196874864-2653ae50-c90d-4794-9bee-88aab858c23b.png)
In actual youtube, there is an effect when we hover over the tags below the search bar as you can see in the above picture.
![ytwr](https://user-images.githubusercontent.com/95235016/196878515-e5a2e4d0-841c-4d08-a0fe-1de3ed7741c6.png)
In this youtube clone, there is no such effect when we hover over these tags.
Can I fix this issue?

**Comment by priyanshumaitra** [comment]
@skk401 Thanks for showing interest in contributing to this repo. The change you mentioned above has been implemented in [this PR](https://github.com/priyanshumaitra/YouTube-Clone/pull/21)
