### ISSUE TITLE
I would like to fix all css

### ISSUE THREAD

**Issue by ujen5173** [priyanshumaitra/YouTube-Clone#24]

**Comment by priyanshumaitra** [comment]
@ujen5173 Thanks for showing interest in contributing to this repo. Do you have any plan or something about how are you going to fix, and what are you going to fix?

**Comment by ujen5173** [comment]
@priyanshumaitra center the categories bar, fix card responsive design, fix input focus css, etc...

**Comment by priyanshumaitra** [comment]
@ujen5173 There's already an issue assigned to someone to make the site responsive.

And by categories, do you mean this chips section? :point_down: 

![image](https://user-images.githubusercontent.com/26964412/196888314-defe4ddd-79aa-4b7d-bf78-54ddd70d37b5.png)

**Comment by ujen5173** [comment]
@priyanshumaitra yes. ohh then i will fix the card responsive

**Comment by priyanshumaitra** [comment]
@ujen5173 You mean the video recommendation section?

**Comment by ujen5173** [comment]
This one:

![image](https://user-images.githubusercontent.com/115857092/196889543-4a437385-a9b1-4b72-aaf1-9192a619c925.png)

**Comment by ujen5173** [comment]
@priyanshumaitra ohh, So is there anything i can help?

**Comment by ujen5173** [comment]
@priyanshumaitra Sure. :)

**Comment by priyanshumaitra** [comment]
> @priyanshumaitra Sure. :)

Okay, then raise a new issue regarding that, and I'll assign you :D
